name: minesweeper
description: A flutter-web project for tokenx by John Blanchard

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any

  cupertino_icons: ^0.1.2
  provider: ^3.1.0

dev_dependencies:
  build_web_compilers:

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web

  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

flutter:

  uses-material-design: true
